spring.application.name=Task-Tracker

spring.profiles.active=dev,prod

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/demo-tasks
spring.datasource.username=postgres
spring.datasource.password=abdo@26016
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tasktracker.max-tasks=50
tasktracker.default-page-size=10


spring.devtools.livereload.enabled=true

logging.level.com.example.shop=DEBUG

# Actuator
management.endpoints.web.exposure.include= health, info, metrics
management.info.env.enabled=true

info.app.name=Task Tracker
info.app.version=1.0.0